name: 'user_service'
services:
  db_2:
    image: 'postgres'
    container_name: db_2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UserServiceDatabase
    ports:
      - "5434:5432"

  app_2:
    build:
      context: ../UserService
      dockerfile: Dockerfile
    container_name: app_2
    depends_on:
      - db_2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.112:5434/UserServiceDatabase
      #      - SPRING_DATASOURCE_USERNAME=$postgres
      #      - SPRING_DATASOURCE_PASSWORD=$postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8082:8082"