spring:
  application:
    name: movie_screening_service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://192.168.0.112:5435/MovieScreeningServiceDatabase
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8083
springdoc:
  paths-to-match: /project/**